# Generated by Django 5.0.6 on 2024-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_setPrice',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
